# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/cole/Documents/SoC/SoC.srcs/sources_1/ip/main_memory/main_memory.xci
# IP: The module: 'main_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cole/Documents/SoC/SoC.srcs/sources_1/ip/main_memory/main_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_memory'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/cole/Documents/SoC/SoC.srcs/sources_1/ip/main_memory/main_memory.xci
# IP: The module: 'main_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cole/Documents/SoC/SoC.srcs/sources_1/ip/main_memory/main_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
